# Generated by Django 5.2.9 on 2026-02-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbs/'),
        ),
    ]
